spring:
  application:
    name: finance-impl

  liquibase:
    change-log: classpath:db/database-changelog-master.yaml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/agona
    hikari:
      password: admin
      username: admin
      maximum-pool-size: 20
      jdbc-url: jdbc:postgresql://localhost:5432/agona

server:
  port: 8081
